networks:
  biodermis-net:
    driver: bridge
    name: biodermis-net

volumes:
  database-data:
    driver: local
  portainer-data:
    driver: local

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    env_file:
      - .env
    ports:
      - ${PORTAINER_PORT}:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data  # Persistência de dados do Portainer
    networks:
      - biodermis-net
    mem_limit: 512m
    memswap_limit: 1g

  database:
    image: postgres:12
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  # Persistência de dados do banco de dados
      - ./backend/Database.sql:/docker-entrypoint-initdb.d/init.sql
    mem_limit: 1g
    memswap_limit: 1g
    networks:
      - biodermis-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - ${PGADMIN_DEFAULT_PORT}:80
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - biodermis-net
    mem_limit: 512m
    memswap_limit: 1g
    depends_on:
      - database

  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - .env
    ports:
      - ${API_PORT}:3000
    environment:
      PORT: ${API_PORT}
      DB_HOST: ${DATABASE_HOST}
      DB_USER: ${DATABASE_USER}
      DB_PASS: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      DB_PORT: ${DATABASE_PORT}
      JWT_PASS: ${JWT_PASS}
      FROM_MAIL: ${FROM_MAIL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      CORS_ORIGIN: ${CORS_ORIGIN}
    mem_limit: 1g
    memswap_limit: 1g
    volumes:
      - ./backend/uploads:/app/uploads  # Persistência de uploads do backend
    depends_on:
      - database
    networks:
      - biodermis-net

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      VITE_API_URL: ${VITE_API_URL}
    mem_limit: 1g
    memswap_limit: 1g  
    networks:
      - biodermis-net

  proxy:
    image: nginx:latest
    container_name: proxy
    restart: always
    env_file:
      - .env
    ports:
      - ${PROXY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - biodermis-net
    depends_on:
      - frontend
